parameters:
    oro_reminder.event_listener.reminder_listener.class: Oro\Bundle\ReminderBundle\EventListener\ReminderListener

services:
    oro_reminder.event_listener.reminder_listener:
        class: %oro_reminder.event_listener.reminder_listener.class%
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_listener, event: postLoad }
