placeholders:
    scripts_after:
        items:
           oro_reminder_subscriber_js:
              order: 10

items:
    oro_reminder_subscriber_js:
        template: OroReminderBundle:Reminder:reminderScripts.html.twig
